spring:
  datasource:
    url: jdbc:mysql://localhost:55001/db_attendance?allowPublicKeyRetrieval=true&allowMultiQueries=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8

mybatis:
  mapperLocations: classpath:com/lyh/manage/mapper/*.xml
logging:
  level:
    com.lyh.manage.dao: debug
server:
  port: 9331
attendance:
  on-time: '08:30'
  off-time: '17:30'
